#ifndef _LIBQUANSHANG_CHANNELS_CHANNEL_H
#define _LIBQUANSHANG_CHANNELS_CHANNEL_H

#define _qdc_CHANNEL_NAME_MAX_CHARACTERS 10 // More cannot fit on radio screen

#define _qdc_Code_TYPE_NONE 0x000
#define _qdc_Code_TYPE_CTCSS 0x100
#define _qdc_Code_TYPE_DCS 0x200
#define _qdc_Code_TYPE_DCS_INVERTED 0x300

typedef enum qdc_Code {
    qdc_Code_NONE = _qdc_Code_TYPE_NONE,

    qdc_Code_CTCSS_67 = _qdc_Code_TYPE_CTCSS | 0x00,
    qdc_Code_CTCSS_69_3 = _qdc_Code_TYPE_CTCSS | 0x01,
    qdc_Code_CTCSS_71_9 = _qdc_Code_TYPE_CTCSS | 0x02,
    qdc_Code_CTCSS_74_4 = _qdc_Code_TYPE_CTCSS | 0x03,
    qdc_Code_CTCSS_77 = _qdc_Code_TYPE_CTCSS | 0x04,
    qdc_Code_CTCSS_79_7 = _qdc_Code_TYPE_CTCSS | 0x05,
    qdc_Code_CTCSS_82_5 = _qdc_Code_TYPE_CTCSS | 0x06,
    qdc_Code_CTCSS_85_4 = _qdc_Code_TYPE_CTCSS | 0x07,
    qdc_Code_CTCSS_88_5 = _qdc_Code_TYPE_CTCSS | 0x08,
    qdc_Code_CTCSS_91_5 = _qdc_Code_TYPE_CTCSS | 0x09,
    qdc_Code_CTCSS_94_8 = _qdc_Code_TYPE_CTCSS | 0x0A,
    qdc_Code_CTCSS_97_4 = _qdc_Code_TYPE_CTCSS | 0x0B,
    qdc_Code_CTCSS_100 = _qdc_Code_TYPE_CTCSS | 0x0C,
    qdc_Code_CTCSS_103_5 = _qdc_Code_TYPE_CTCSS | 0x0D,
    qdc_Code_CTCSS_107_2 = _qdc_Code_TYPE_CTCSS | 0x0E,
    qdc_Code_CTCSS_110_9 = _qdc_Code_TYPE_CTCSS | 0x0F,
    qdc_Code_CTCSS_114_8 = _qdc_Code_TYPE_CTCSS | 0x10,
    qdc_Code_CTCSS_118_8 = _qdc_Code_TYPE_CTCSS | 0x11,
    qdc_Code_CTCSS_123 = _qdc_Code_TYPE_CTCSS | 0x12,
    qdc_Code_CTCSS_127_3 = _qdc_Code_TYPE_CTCSS | 0x13,
    qdc_Code_CTCSS_131_8 = _qdc_Code_TYPE_CTCSS | 0x14,
    qdc_Code_CTCSS_136_5 = _qdc_Code_TYPE_CTCSS | 0x15,
    qdc_Code_CTCSS_141_3 = _qdc_Code_TYPE_CTCSS | 0x16,
    qdc_Code_CTCSS_146_2 = _qdc_Code_TYPE_CTCSS | 0x17,
    qdc_Code_CTCSS_151_4 = _qdc_Code_TYPE_CTCSS | 0x18,
    qdc_Code_CTCSS_156_7 = _qdc_Code_TYPE_CTCSS | 0x19,
    qdc_Code_CTCSS_159_8 = _qdc_Code_TYPE_CTCSS | 0x1A,
    qdc_Code_CTCSS_162_2 = _qdc_Code_TYPE_CTCSS | 0x1B,
    qdc_Code_CTCSS_165_5 = _qdc_Code_TYPE_CTCSS | 0x1C,
    qdc_Code_CTCSS_167_9 = _qdc_Code_TYPE_CTCSS | 0x1D,
    qdc_Code_CTCSS_171_3 = _qdc_Code_TYPE_CTCSS | 0x1E,
    qdc_Code_CTCSS_173_8 = _qdc_Code_TYPE_CTCSS | 0x1F,
    qdc_Code_CTCSS_177_3 = _qdc_Code_TYPE_CTCSS | 0x20,
    qdc_Code_CTCSS_179_9 = _qdc_Code_TYPE_CTCSS | 0x21,
    qdc_Code_CTCSS_183_5 = _qdc_Code_TYPE_CTCSS | 0x22,
    qdc_Code_CTCSS_186_2 = _qdc_Code_TYPE_CTCSS | 0x23,
    qdc_Code_CTCSS_189_9 = _qdc_Code_TYPE_CTCSS | 0x24,
    qdc_Code_CTCSS_192_8 = _qdc_Code_TYPE_CTCSS | 0x25,
    qdc_Code_CTCSS_196_6 = _qdc_Code_TYPE_CTCSS | 0x26,
    qdc_Code_CTCSS_199_5 = _qdc_Code_TYPE_CTCSS | 0x27,
    qdc_Code_CTCSS_203_5 = _qdc_Code_TYPE_CTCSS | 0x28,
    qdc_Code_CTCSS_206_5 = _qdc_Code_TYPE_CTCSS | 0x29,
    qdc_Code_CTCSS_210_7 = _qdc_Code_TYPE_CTCSS | 0x2A,
    qdc_Code_CTCSS_218_1 = _qdc_Code_TYPE_CTCSS | 0x2B,
    qdc_Code_CTCSS_225_7 = _qdc_Code_TYPE_CTCSS | 0x2C,
    qdc_Code_CTCSS_229_1 = _qdc_Code_TYPE_CTCSS | 0x2D,
    qdc_Code_CTCSS_233_6 = _qdc_Code_TYPE_CTCSS | 0x2E,
    qdc_Code_CTCSS_241_8 = _qdc_Code_TYPE_CTCSS | 0x2F,
    qdc_Code_CTCSS_250_3 = _qdc_Code_TYPE_CTCSS | 0x30,
    qdc_Code_CTCSS_254_1 = _qdc_Code_TYPE_CTCSS | 0x31,

    qdc_Code_DCS_23 = _qdc_Code_TYPE_DCS | 0x00,
    qdc_Code_DCS_25 = _qdc_Code_TYPE_DCS | 0x01,
    qdc_Code_DCS_26 = _qdc_Code_TYPE_DCS | 0x02,
    qdc_Code_DCS_31 = _qdc_Code_TYPE_DCS | 0x03,
    qdc_Code_DCS_32 = _qdc_Code_TYPE_DCS | 0x04,
    qdc_Code_DCS_36 = _qdc_Code_TYPE_DCS | 0x05,
    qdc_Code_DCS_43 = _qdc_Code_TYPE_DCS | 0x06,
    qdc_Code_DCS_47 = _qdc_Code_TYPE_DCS | 0x07,
    qdc_Code_DCS_51 = _qdc_Code_TYPE_DCS | 0x08,
    qdc_Code_DCS_53 = _qdc_Code_TYPE_DCS | 0x09,
    qdc_Code_DCS_54 = _qdc_Code_TYPE_DCS | 0x0A,
    qdc_Code_DCS_65 = _qdc_Code_TYPE_DCS | 0x0B,
    qdc_Code_DCS_71 = _qdc_Code_TYPE_DCS | 0x0C,
    qdc_Code_DCS_72 = _qdc_Code_TYPE_DCS | 0x0D,
    qdc_Code_DCS_73 = _qdc_Code_TYPE_DCS | 0x0E,
    qdc_Code_DCS_74 = _qdc_Code_TYPE_DCS | 0x0F,
    qdc_Code_DCS_114 = _qdc_Code_TYPE_DCS | 0x10,
    qdc_Code_DCS_115 = _qdc_Code_TYPE_DCS | 0x11,
    qdc_Code_DCS_116 = _qdc_Code_TYPE_DCS | 0x12,
    qdc_Code_DCS_122 = _qdc_Code_TYPE_DCS | 0x13,
    qdc_Code_DCS_125 = _qdc_Code_TYPE_DCS | 0x14,
    qdc_Code_DCS_131 = _qdc_Code_TYPE_DCS | 0x15,
    qdc_Code_DCS_132 = _qdc_Code_TYPE_DCS | 0x16,
    qdc_Code_DCS_134 = _qdc_Code_TYPE_DCS | 0x17,
    qdc_Code_DCS_143 = _qdc_Code_TYPE_DCS | 0x18,
    qdc_Code_DCS_145 = _qdc_Code_TYPE_DCS | 0x19,
    qdc_Code_DCS_152 = _qdc_Code_TYPE_DCS | 0x1A,
    qdc_Code_DCS_155 = _qdc_Code_TYPE_DCS | 0x1B,
    qdc_Code_DCS_156 = _qdc_Code_TYPE_DCS | 0x1C,
    qdc_Code_DCS_162 = _qdc_Code_TYPE_DCS | 0x1D,
    qdc_Code_DCS_165 = _qdc_Code_TYPE_DCS | 0x1E,
    qdc_Code_DCS_172 = _qdc_Code_TYPE_DCS | 0x1F,
    qdc_Code_DCS_174 = _qdc_Code_TYPE_DCS | 0x20,
    qdc_Code_DCS_205 = _qdc_Code_TYPE_DCS | 0x21,
    qdc_Code_DCS_212 = _qdc_Code_TYPE_DCS | 0x22,
    qdc_Code_DCS_223 = _qdc_Code_TYPE_DCS | 0x23,
    qdc_Code_DCS_225 = _qdc_Code_TYPE_DCS | 0x24,
    qdc_Code_DCS_226 = _qdc_Code_TYPE_DCS | 0x25,
    qdc_Code_DCS_243 = _qdc_Code_TYPE_DCS | 0x26,
    qdc_Code_DCS_244 = _qdc_Code_TYPE_DCS | 0x27,
    qdc_Code_DCS_245 = _qdc_Code_TYPE_DCS | 0x28,
    qdc_Code_DCS_246 = _qdc_Code_TYPE_DCS | 0x29,
    qdc_Code_DCS_251 = _qdc_Code_TYPE_DCS | 0x2A,
    qdc_Code_DCS_252 = _qdc_Code_TYPE_DCS | 0x2B,
    qdc_Code_DCS_255 = _qdc_Code_TYPE_DCS | 0x2C,
    qdc_Code_DCS_261 = _qdc_Code_TYPE_DCS | 0x2D,
    qdc_Code_DCS_263 = _qdc_Code_TYPE_DCS | 0x2E,
    qdc_Code_DCS_265 = _qdc_Code_TYPE_DCS | 0x2F,
    qdc_Code_DCS_266 = _qdc_Code_TYPE_DCS | 0x30,
    qdc_Code_DCS_271 = _qdc_Code_TYPE_DCS | 0x31,
    qdc_Code_DCS_274 = _qdc_Code_TYPE_DCS | 0x32,
    qdc_Code_DCS_306 = _qdc_Code_TYPE_DCS | 0x33,
    qdc_Code_DCS_311 = _qdc_Code_TYPE_DCS | 0x34,
    qdc_Code_DCS_315 = _qdc_Code_TYPE_DCS | 0x35,
    qdc_Code_DCS_325 = _qdc_Code_TYPE_DCS | 0x36,
    qdc_Code_DCS_331 = _qdc_Code_TYPE_DCS | 0x37,
    qdc_Code_DCS_332 = _qdc_Code_TYPE_DCS | 0x38,
    qdc_Code_DCS_343 = _qdc_Code_TYPE_DCS | 0x39,
    qdc_Code_DCS_346 = _qdc_Code_TYPE_DCS | 0x3A,
    qdc_Code_DCS_351 = _qdc_Code_TYPE_DCS | 0x3B,
    qdc_Code_DCS_356 = _qdc_Code_TYPE_DCS | 0x3C,
    qdc_Code_DCS_364 = _qdc_Code_TYPE_DCS | 0x3D,
    qdc_Code_DCS_365 = _qdc_Code_TYPE_DCS | 0x3E,
    qdc_Code_DCS_371 = _qdc_Code_TYPE_DCS | 0x3F,
    qdc_Code_DCS_411 = _qdc_Code_TYPE_DCS | 0x40,
    qdc_Code_DCS_412 = _qdc_Code_TYPE_DCS | 0x41,
    qdc_Code_DCS_413 = _qdc_Code_TYPE_DCS | 0x42,
    qdc_Code_DCS_423 = _qdc_Code_TYPE_DCS | 0x43,
    qdc_Code_DCS_431 = _qdc_Code_TYPE_DCS | 0x44,
    qdc_Code_DCS_432 = _qdc_Code_TYPE_DCS | 0x45,
    qdc_Code_DCS_445 = _qdc_Code_TYPE_DCS | 0x46,
    qdc_Code_DCS_446 = _qdc_Code_TYPE_DCS | 0x47,
    qdc_Code_DCS_452 = _qdc_Code_TYPE_DCS | 0x48,
    qdc_Code_DCS_454 = _qdc_Code_TYPE_DCS | 0x49,
    qdc_Code_DCS_455 = _qdc_Code_TYPE_DCS | 0x4A,
    qdc_Code_DCS_462 = _qdc_Code_TYPE_DCS | 0x4B,
    qdc_Code_DCS_464 = _qdc_Code_TYPE_DCS | 0x4C,
    qdc_Code_DCS_465 = _qdc_Code_TYPE_DCS | 0x4D,
    qdc_Code_DCS_466 = _qdc_Code_TYPE_DCS | 0x4E,
    qdc_Code_DCS_503 = _qdc_Code_TYPE_DCS | 0x4F,
    qdc_Code_DCS_506 = _qdc_Code_TYPE_DCS | 0x50,
    qdc_Code_DCS_516 = _qdc_Code_TYPE_DCS | 0x51,
    qdc_Code_DCS_523 = _qdc_Code_TYPE_DCS | 0x52,
    qdc_Code_DCS_526 = _qdc_Code_TYPE_DCS | 0x53,
    qdc_Code_DCS_532 = _qdc_Code_TYPE_DCS | 0x54,
    qdc_Code_DCS_546 = _qdc_Code_TYPE_DCS | 0x55,
    qdc_Code_DCS_565 = _qdc_Code_TYPE_DCS | 0x56,
    qdc_Code_DCS_606 = _qdc_Code_TYPE_DCS | 0x57,
    qdc_Code_DCS_612 = _qdc_Code_TYPE_DCS | 0x58,
    qdc_Code_DCS_624 = _qdc_Code_TYPE_DCS | 0x59,
    qdc_Code_DCS_627 = _qdc_Code_TYPE_DCS | 0x5A,
    qdc_Code_DCS_631 = _qdc_Code_TYPE_DCS | 0x5B,
    qdc_Code_DCS_632 = _qdc_Code_TYPE_DCS | 0x5C,
    qdc_Code_DCS_654 = _qdc_Code_TYPE_DCS | 0x5D,
    qdc_Code_DCS_662 = _qdc_Code_TYPE_DCS | 0x5E,
    qdc_Code_DCS_664 = _qdc_Code_TYPE_DCS | 0x5F,
    qdc_Code_DCS_703 = _qdc_Code_TYPE_DCS | 0x60,
    qdc_Code_DCS_712 = _qdc_Code_TYPE_DCS | 0x61,
    qdc_Code_DCS_723 = _qdc_Code_TYPE_DCS | 0x62,
    qdc_Code_DCS_731 = _qdc_Code_TYPE_DCS | 0x63,
    qdc_Code_DCS_732 = _qdc_Code_TYPE_DCS | 0x64,
    qdc_Code_DCS_734 = _qdc_Code_TYPE_DCS | 0x65,
    qdc_Code_DCS_743 = _qdc_Code_TYPE_DCS | 0x66,
    qdc_Code_DCS_754 = _qdc_Code_TYPE_DCS | 0x67,

    qdc_Code_DCS_INVERTED_23 = _qdc_Code_TYPE_DCS_INVERTED | 0x00,
    qdc_Code_DCS_INVERTED_25 = _qdc_Code_TYPE_DCS_INVERTED | 0x01,
    qdc_Code_DCS_INVERTED_26 = _qdc_Code_TYPE_DCS_INVERTED | 0x02,
    qdc_Code_DCS_INVERTED_31 = _qdc_Code_TYPE_DCS_INVERTED | 0x03,
    qdc_Code_DCS_INVERTED_32 = _qdc_Code_TYPE_DCS_INVERTED | 0x04,
    qdc_Code_DCS_INVERTED_36 = _qdc_Code_TYPE_DCS_INVERTED | 0x05,
    qdc_Code_DCS_INVERTED_43 = _qdc_Code_TYPE_DCS_INVERTED | 0x06,
    qdc_Code_DCS_INVERTED_47 = _qdc_Code_TYPE_DCS_INVERTED | 0x07,
    qdc_Code_DCS_INVERTED_51 = _qdc_Code_TYPE_DCS_INVERTED | 0x08,
    qdc_Code_DCS_INVERTED_53 = _qdc_Code_TYPE_DCS_INVERTED | 0x09,
    qdc_Code_DCS_INVERTED_54 = _qdc_Code_TYPE_DCS_INVERTED | 0x0A,
    qdc_Code_DCS_INVERTED_65 = _qdc_Code_TYPE_DCS_INVERTED | 0x0B,
    qdc_Code_DCS_INVERTED_71 = _qdc_Code_TYPE_DCS_INVERTED | 0x0C,
    qdc_Code_DCS_INVERTED_72 = _qdc_Code_TYPE_DCS_INVERTED | 0x0D,
    qdc_Code_DCS_INVERTED_73 = _qdc_Code_TYPE_DCS_INVERTED | 0x0E,
    qdc_Code_DCS_INVERTED_74 = _qdc_Code_TYPE_DCS_INVERTED | 0x0F,
    qdc_Code_DCS_INVERTED_114 = _qdc_Code_TYPE_DCS_INVERTED | 0x10,
    qdc_Code_DCS_INVERTED_115 = _qdc_Code_TYPE_DCS_INVERTED | 0x11,
    qdc_Code_DCS_INVERTED_116 = _qdc_Code_TYPE_DCS_INVERTED | 0x12,
    qdc_Code_DCS_INVERTED_122 = _qdc_Code_TYPE_DCS_INVERTED | 0x13,
    qdc_Code_DCS_INVERTED_125 = _qdc_Code_TYPE_DCS_INVERTED | 0x14,
    qdc_Code_DCS_INVERTED_131 = _qdc_Code_TYPE_DCS_INVERTED | 0x15,
    qdc_Code_DCS_INVERTED_132 = _qdc_Code_TYPE_DCS_INVERTED | 0x16,
    qdc_Code_DCS_INVERTED_134 = _qdc_Code_TYPE_DCS_INVERTED | 0x17,
    qdc_Code_DCS_INVERTED_143 = _qdc_Code_TYPE_DCS_INVERTED | 0x18,
    qdc_Code_DCS_INVERTED_145 = _qdc_Code_TYPE_DCS_INVERTED | 0x19,
    qdc_Code_DCS_INVERTED_152 = _qdc_Code_TYPE_DCS_INVERTED | 0x1A,
    qdc_Code_DCS_INVERTED_155 = _qdc_Code_TYPE_DCS_INVERTED | 0x1B,
    qdc_Code_DCS_INVERTED_156 = _qdc_Code_TYPE_DCS_INVERTED | 0x1C,
    qdc_Code_DCS_INVERTED_162 = _qdc_Code_TYPE_DCS_INVERTED | 0x1D,
    qdc_Code_DCS_INVERTED_165 = _qdc_Code_TYPE_DCS_INVERTED | 0x1E,
    qdc_Code_DCS_INVERTED_172 = _qdc_Code_TYPE_DCS_INVERTED | 0x1F,
    qdc_Code_DCS_INVERTED_174 = _qdc_Code_TYPE_DCS_INVERTED | 0x20,
    qdc_Code_DCS_INVERTED_205 = _qdc_Code_TYPE_DCS_INVERTED | 0x21,
    qdc_Code_DCS_INVERTED_212 = _qdc_Code_TYPE_DCS_INVERTED | 0x22,
    qdc_Code_DCS_INVERTED_223 = _qdc_Code_TYPE_DCS_INVERTED | 0x23,
    qdc_Code_DCS_INVERTED_225 = _qdc_Code_TYPE_DCS_INVERTED | 0x24,
    qdc_Code_DCS_INVERTED_226 = _qdc_Code_TYPE_DCS_INVERTED | 0x25,
    qdc_Code_DCS_INVERTED_243 = _qdc_Code_TYPE_DCS_INVERTED | 0x26,
    qdc_Code_DCS_INVERTED_244 = _qdc_Code_TYPE_DCS_INVERTED | 0x27,
    qdc_Code_DCS_INVERTED_245 = _qdc_Code_TYPE_DCS_INVERTED | 0x28,
    qdc_Code_DCS_INVERTED_246 = _qdc_Code_TYPE_DCS_INVERTED | 0x29,
    qdc_Code_DCS_INVERTED_251 = _qdc_Code_TYPE_DCS_INVERTED | 0x2A,
    qdc_Code_DCS_INVERTED_252 = _qdc_Code_TYPE_DCS_INVERTED | 0x2B,
    qdc_Code_DCS_INVERTED_255 = _qdc_Code_TYPE_DCS_INVERTED | 0x2C,
    qdc_Code_DCS_INVERTED_261 = _qdc_Code_TYPE_DCS_INVERTED | 0x2D,
    qdc_Code_DCS_INVERTED_263 = _qdc_Code_TYPE_DCS_INVERTED | 0x2E,
    qdc_Code_DCS_INVERTED_265 = _qdc_Code_TYPE_DCS_INVERTED | 0x2F,
    qdc_Code_DCS_INVERTED_266 = _qdc_Code_TYPE_DCS_INVERTED | 0x30,
    qdc_Code_DCS_INVERTED_271 = _qdc_Code_TYPE_DCS_INVERTED | 0x31,
    qdc_Code_DCS_INVERTED_274 = _qdc_Code_TYPE_DCS_INVERTED | 0x32,
    qdc_Code_DCS_INVERTED_306 = _qdc_Code_TYPE_DCS_INVERTED | 0x33,
    qdc_Code_DCS_INVERTED_311 = _qdc_Code_TYPE_DCS_INVERTED | 0x34,
    qdc_Code_DCS_INVERTED_315 = _qdc_Code_TYPE_DCS_INVERTED | 0x35,
    qdc_Code_DCS_INVERTED_325 = _qdc_Code_TYPE_DCS_INVERTED | 0x36,
    qdc_Code_DCS_INVERTED_331 = _qdc_Code_TYPE_DCS_INVERTED | 0x37,
    qdc_Code_DCS_INVERTED_332 = _qdc_Code_TYPE_DCS_INVERTED | 0x38,
    qdc_Code_DCS_INVERTED_343 = _qdc_Code_TYPE_DCS_INVERTED | 0x39,
    qdc_Code_DCS_INVERTED_346 = _qdc_Code_TYPE_DCS_INVERTED | 0x3A,
    qdc_Code_DCS_INVERTED_351 = _qdc_Code_TYPE_DCS_INVERTED | 0x3B,
    qdc_Code_DCS_INVERTED_356 = _qdc_Code_TYPE_DCS_INVERTED | 0x3C,
    qdc_Code_DCS_INVERTED_364 = _qdc_Code_TYPE_DCS_INVERTED | 0x3D,
    qdc_Code_DCS_INVERTED_365 = _qdc_Code_TYPE_DCS_INVERTED | 0x3E,
    qdc_Code_DCS_INVERTED_371 = _qdc_Code_TYPE_DCS_INVERTED | 0x3F,
    qdc_Code_DCS_INVERTED_411 = _qdc_Code_TYPE_DCS_INVERTED | 0x40,
    qdc_Code_DCS_INVERTED_412 = _qdc_Code_TYPE_DCS_INVERTED | 0x41,
    qdc_Code_DCS_INVERTED_413 = _qdc_Code_TYPE_DCS_INVERTED | 0x42,
    qdc_Code_DCS_INVERTED_423 = _qdc_Code_TYPE_DCS_INVERTED | 0x43,
    qdc_Code_DCS_INVERTED_431 = _qdc_Code_TYPE_DCS_INVERTED | 0x44,
    qdc_Code_DCS_INVERTED_432 = _qdc_Code_TYPE_DCS_INVERTED | 0x45,
    qdc_Code_DCS_INVERTED_445 = _qdc_Code_TYPE_DCS_INVERTED | 0x46,
    qdc_Code_DCS_INVERTED_446 = _qdc_Code_TYPE_DCS_INVERTED | 0x47,
    qdc_Code_DCS_INVERTED_452 = _qdc_Code_TYPE_DCS_INVERTED | 0x48,
    qdc_Code_DCS_INVERTED_454 = _qdc_Code_TYPE_DCS_INVERTED | 0x49,
    qdc_Code_DCS_INVERTED_455 = _qdc_Code_TYPE_DCS_INVERTED | 0x4A,
    qdc_Code_DCS_INVERTED_462 = _qdc_Code_TYPE_DCS_INVERTED | 0x4B,
    qdc_Code_DCS_INVERTED_464 = _qdc_Code_TYPE_DCS_INVERTED | 0x4C,
    qdc_Code_DCS_INVERTED_465 = _qdc_Code_TYPE_DCS_INVERTED | 0x4D,
    qdc_Code_DCS_INVERTED_466 = _qdc_Code_TYPE_DCS_INVERTED | 0x4E,
    qdc_Code_DCS_INVERTED_503 = _qdc_Code_TYPE_DCS_INVERTED | 0x4F,
    qdc_Code_DCS_INVERTED_506 = _qdc_Code_TYPE_DCS_INVERTED | 0x50,
    qdc_Code_DCS_INVERTED_516 = _qdc_Code_TYPE_DCS_INVERTED | 0x51,
    qdc_Code_DCS_INVERTED_523 = _qdc_Code_TYPE_DCS_INVERTED | 0x52,
    qdc_Code_DCS_INVERTED_526 = _qdc_Code_TYPE_DCS_INVERTED | 0x53,
    qdc_Code_DCS_INVERTED_532 = _qdc_Code_TYPE_DCS_INVERTED | 0x54,
    qdc_Code_DCS_INVERTED_546 = _qdc_Code_TYPE_DCS_INVERTED | 0x55,
    qdc_Code_DCS_INVERTED_565 = _qdc_Code_TYPE_DCS_INVERTED | 0x56,
    qdc_Code_DCS_INVERTED_606 = _qdc_Code_TYPE_DCS_INVERTED | 0x57,
    qdc_Code_DCS_INVERTED_612 = _qdc_Code_TYPE_DCS_INVERTED | 0x58,
    qdc_Code_DCS_INVERTED_624 = _qdc_Code_TYPE_DCS_INVERTED | 0x59,
    qdc_Code_DCS_INVERTED_627 = _qdc_Code_TYPE_DCS_INVERTED | 0x5A,
    qdc_Code_DCS_INVERTED_631 = _qdc_Code_TYPE_DCS_INVERTED | 0x5B,
    qdc_Code_DCS_INVERTED_632 = _qdc_Code_TYPE_DCS_INVERTED | 0x5C,
    qdc_Code_DCS_INVERTED_654 = _qdc_Code_TYPE_DCS_INVERTED | 0x5D,
    qdc_Code_DCS_INVERTED_662 = _qdc_Code_TYPE_DCS_INVERTED | 0x5E,
    qdc_Code_DCS_INVERTED_664 = _qdc_Code_TYPE_DCS_INVERTED | 0x5F,
    qdc_Code_DCS_INVERTED_703 = _qdc_Code_TYPE_DCS_INVERTED | 0x60,
    qdc_Code_DCS_INVERTED_712 = _qdc_Code_TYPE_DCS_INVERTED | 0x61,
    qdc_Code_DCS_INVERTED_723 = _qdc_Code_TYPE_DCS_INVERTED | 0x62,
    qdc_Code_DCS_INVERTED_731 = _qdc_Code_TYPE_DCS_INVERTED | 0x63,
    qdc_Code_DCS_INVERTED_732 = _qdc_Code_TYPE_DCS_INVERTED | 0x64,
    qdc_Code_DCS_INVERTED_734 = _qdc_Code_TYPE_DCS_INVERTED | 0x65,
    qdc_Code_DCS_INVERTED_743 = _qdc_Code_TYPE_DCS_INVERTED | 0x66,
    qdc_Code_DCS_INVERTED_754 = _qdc_Code_TYPE_DCS_INVERTED | 0x67,
} qdc_Code;

typedef enum qdc_Modulation {
    qdc_Modulation_FM = 0x0,
    qdc_Modulation_AM = 0x1,
    qdc_Modulation_USB = 0x2,
} qdc_Modulation;

typedef enum qdc_OffsetDirection {
    qdc_OffsetDirection_NONE = 0x0,
    qdc_OffsetDirection_PLUS = 0x1,
    qdc_OffsetDirection_MINUS = 0x2,
} qdc_OffsetDirection;

typedef enum qdc_OutputPower {
    qdc_OutputPower_LOW = 0x0,
    qdc_OutputPower_MEDIUM = 0x1,
    qdc_OutputPower_HIGH = 0x2,
} qdc_OutputPower;

typedef enum qdc_Bandwidth {
    qdc_Bandwidth_WIDE = 0x0,
    qdc_Bandwidth_NARROW = 0x1,
} qdc_Bandwidth;

typedef enum qdc_PttIdMode {
    qdc_PttId_NONE = 0b000,
    qdc_PttId_BEGIN = 0b001,
    qdc_PttId_END = 0b010,
    qdc_PttId_BEGIN_END = 0b011,
    qdc_PttId_APOLLO_QUINDAR = 0b100,
} qdc_PttIdMode;

typedef enum qdc_FrequencyStep {
    qdc_FrequencyStep_0_01 = 0x07,
    qdc_FrequencyStep_0_05 = 0x08,
    qdc_FrequencyStep_0_1 = 0x09,
    qdc_FrequencyStep_0_25 = 0x0A,
    qdc_FrequencyStep_0_5 = 0x0B,
    qdc_FrequencyStep_1 = 0x0C,
    qdc_FrequencyStep_1_25 = 0x0D,
    qdc_FrequencyStep_2_5 = 0x00,
    qdc_FrequencyStep_5 = 0x01,
    qdc_FrequencyStep_6_25 = 0x02,
    qdc_FrequencyStep_8_33 = 0x06,
    qdc_FrequencyStep_10 = 0x03,
    qdc_FrequencyStep_12_5 = 0x04,
    qdc_FrequencyStep_15 = 0x0E,
    qdc_FrequencyStep_25 = 0x05,
    qdc_FrequencyStep_30 = 0x0F,
    qdc_FrequencyStep_50 = 0x10,
    qdc_FrequencyStep_100 = 0x11,
    qdc_FrequencyStep_125 = 0x12,
    qdc_FrequencyStep_250 = 0x13,
    qdc_FrequencyStep_500 = 0x14,
} qdc_FrequencyStep;

typedef enum qdc_ScrambleMode {
    qdc_Scramble_NONE = 0x00,
    qdc_Scramble_2600 = 0x01,
    qdc_Scramble_2700 = 0x02,
    qdc_Scramble_2800 = 0x03,
    qdc_Scramble_2900 = 0x04,
    qdc_Scramble_3000 = 0x05,
    qdc_Scramble_3100 = 0x06,
    qdc_Scramble_3200 = 0x07,
    qdc_Scramble_3300 = 0x08,
    qdc_Scramble_3400 = 0x09,
    qdc_Scramble_3500 = 0x0A,
} qdc_ScrambleMode;

typedef struct qdc_Channel {
    unsigned long rxFrequency;
    unsigned int txOffset;
    qdc_Code txCode;
    qdc_Code rxCode;
    qdc_Modulation modulation;
    qdc_OffsetDirection offsetDirection;
    _Bool preventTxWhileReceiving;
    qdc_OutputPower outputPower;
    qdc_Bandwidth bandwidth;
    _Bool swapRxAndTxFrequencies;
    qdc_PttIdMode pttIdMode;
    _Bool enableDtmf;
    qdc_FrequencyStep frequencyStep;
    qdc_ScrambleMode scrambleMode;
    char name[_qdc_CHANNEL_NAME_MAX_CHARACTERS + 1];
    _Bool includeInScanList1;
    _Bool includeInScanList2;
    _Bool enableTxCompander;
    _Bool enableRxCompander;
} qdc_Channel;

#endif
